apiVersion: v1
kind: Service
metadata:
  name: {{ include "realtime-chat.fullname" . }}
  labels:
    {{- include "realtime-chat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    {{- include "realtime-chat.selectorLabels" . | nindent 4 }}
