apiVersion: v2
name: glitchtip
description: GlitchTip error tracking with PostgreSQL
type: application
version: 0.1.1
appVersion: "5.2.1"

dependencies:
  - name: postgresql
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
  - name: glitchtip
    version: "7.1.0"
    repository: https://gitlab.com/api/v4/projects/16325141/packages/helm/stable
