apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
data:
  turnserver.conf: |
    tls-listening-port=5349
    listening-port=5349
    no-udp
    cert=/etc/coturn/tls/tls.crt
    pkey=/etc/coturn/tls/tls.key
    fingerprint
    realm={{ .Values.realm }}
    external-ip={{ .Values.externalIp }}/{{ include "coturn.fullname" . }}
    no-ipv6
    verbose

    use-auth-secret
    static-auth-secret={{ .Values.secret }}