apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/wildcard.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "files/wildcard.key" | b64enc | quote }}